LISTINGS = [
    {
        "id": 1,
        "title": "Mélangeur de digesteur inox 30 kW",
        "category": "Agitation",
        "location": "Bretagne, FR",
        "price": "12 900 €",
        "condition": "Très bon état",
        "summary": "Mélangeur vertical inox 316L, 30 kW, 2019.",
        "image": "https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?w=1200&q=80",
    },
    {
        "id": 2,
        "title": "Pompe à membrane pour digestat",
        "category": "Pompage",
        "location": "Grand Est, FR",
        "price": "6 400 €",
        "condition": "Révisé",
        "summary": "Pompe à membrane 12 m³/h, étanchéité renforcée.",
        "image": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1200&q=80",
    },
    {
        "id": 3,
        "title": "Module d’épuration biogaz PSA 300 Nm³/h",
        "category": "Épuration",
        "location": "Wallonie, BE",
        "price": "Sur devis",
        "condition": "Neuf",
        "summary": "Unité PSA complète, automatisation incluse.",
        "image": "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?w=1200&q=80",
    },
    {
        "id": 4,
        "title": "Torchère biogaz 1 200 Nm³/h",
        "category": "Sécurité",
        "location": "Bavière, DE",
        "price": "9 800 €",
        "condition": "Bon état",
        "summary": "Torchère à flare fermé, 2017.",
        "image": "https://images.unsplash.com/photo-1497436072909-60f360e1d4b1?w=1200&q=80",
    },
    {
        "id": 5,
        "title": "Échangeur thermique inox 250 kW",
        "category": "Thermique",
        "location": "Normandie, FR",
        "price": "4 300 €",
        "condition": "Comme neuf",
        "summary": "Échangeur à plaques, haute performance.",
        "image": "https://images.unsplash.com/photo-1482192596544-9eb780fc7f66?w=1200&q=80",
    },
    {
        "id": 6,
        "title": "Automate de contrôle process biogaz",
        "category": "Automatisme",
        "location": "Hauts-de-France, FR",
        "price": "2 900 €",
        "condition": "Reconditionné",
        "summary": "PLC + supervision, historique complet.",
        "image": "https://images.unsplash.com/photo-1487058792275-0ad4aaf24ca7?w=1200&q=80",
    },
]