LISTINGS = [
    {
        "id": 1,
        "title": "Mélangeur de digesteur inox 30 kW",
        "category": "Agitation",
        "location": "Bretagne, FR",
        "price": "12 900 €",
        "condition": "Très bon état",
        "summary": "Mélangeur vertical inox 316L, 30 kW, 2019.",
        "description": "Mélangeur submersible vertical en acier inoxydable 316L de haute qualité. Puissance nominale 30 kW, conçu pour digesteurs de méthanisation. Fabriqué en 2019, en très bon état avec maintenance régulière effectuée. Longueur totale 4,5m, diamètre hélice 1200mm. Testé et garanti fonctionnel. Disponible immédiatement.",
        "year": "2019",
        "manufacturer": "Landia",
        "contact_email": "bretagne.methanisation@example.fr",
        "contact_phone": "+33 2 98 XX XX XX",
        "image": "https://images.unsplash.com/photo-1581092918484-8313e1f7e8d6?w=1200&q=80",
    },
    {
        "id": 2,
        "title": "Pompe à membrane pour digestat",
        "category": "Pompage",
        "location": "Grand Est, FR",
        "price": "6 400 €",
        "condition": "Révisé",
        "summary": "Pompe à membrane 12 m³/h, étanchéité renforcée.",
        "description": "Pompe volumétrique à membrane double effet pour le transfert de digestat. Débit nominal 12 m³/h, pression maximale 8 bars. Révision complète effectuée récemment (membranes, clapets, joints). Matériaux compatibles avec environnement biogaz. Parfait pour installations de méthanisation jusqu'à 500 kWe. Garantie 6 mois.",
        "year": "2017",
        "manufacturer": "Vogelsang",
        "contact_email": "contact.grandest@example.fr",
        "contact_phone": "+33 3 88 XX XX XX",
        "image": "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=1200&q=80",
    },
    {
        "id": 3,
        "title": "Module d'épuration biogaz PSA 300 Nm³/h",
        "category": "Épuration",
        "location": "Wallonie, BE",
        "price": "Sur devis",
        "condition": "Neuf",
        "summary": "Unité PSA complète, automatisation incluse.",
        "description": "Unité d'épuration biogaz par technologie PSA (Pressure Swing Adsorption) neuve, capacité 300 Nm³/h. Production de biométhane qualité réseau. Système complet incluant compresseurs, colonnes de séchage, colonnes de tamis moléculaire, automatisation Siemens S7, analyse en ligne. Conformité normative EU. Installation et mise en service incluses. Délai de livraison 12 semaines.",
        "year": "2026",
        "manufacturer": "CarboTech",
        "contact_email": "sales@carbotech-be.example",
        "contact_phone": "+32 4 XXX XX XX",
        "image": "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=1200&q=80",
    },
    {
        "id": 4,
        "title": "Torchère biogaz 1 200 Nm³/h",
        "category": "Sécurité",
        "location": "Bavière, DE",
        "price": "9 800 €",
        "condition": "Bon état",
        "summary": "Torchère à flare fermé, 2017.",
        "description": "Torchère de sécurité à flamme fermée, capacité maximale 1200 Nm³/h biogaz. Installation en 2017, démontée d'un site en restructuration. Fonctionnement automatique avec détection flamme, allumage piézo. Conformité ATEX. Brûleur inox réfractaire, structure acier galvanisé. Documentation technique complète fournie.",
        "year": "2017",
        "manufacturer": "MWM/HOFGAS",
        "contact_email": "verkauf@biogas-bayern.example",
        "contact_phone": "+49 89 XXXX XXXX",
        "image": "https://images.unsplash.com/photo-1581092160607-ee5c91aaa2f4?w=1200&q=80",
    },
    {
        "id": 5,
        "title": "Échangeur thermique inox 250 kW",
        "category": "Thermique",
        "location": "Normandie, FR",
        "price": "4 300 €",
        "condition": "Comme neuf",
        "summary": "Échangeur à plaques, haute performance.",
        "description": "Échangeur de chaleur à plaques brasées en acier inoxydable 316, puissance thermique 250 kW. Très peu utilisé (6 mois), état quasi neuf. Idéal pour valorisation chaleur biogaz/cogénération. Surface d'échange optimisée, perte de charge minimale. Raccords DN50, pression max 30 bars. Nettoyage et test hydraulique effectués.",
        "year": "2024",
        "manufacturer": "Alfa Laval",
        "contact_email": "normandie.energie@example.fr",
        "contact_phone": "+33 2 35 XX XX XX",
        "image": "https://images.unsplash.com/photo-1581092918484-8be0ec6e7b3d?w=1200&q=80",
    },
    {
        "id": 6,
        "title": "Automate de contrôle process biogaz",
        "category": "Automatisme",
        "location": "Hauts-de-France, FR",
        "price": "2 900 €",
        "condition": "Reconditionné",
        "summary": "PLC + supervision, historique complet.",
        "description": "Automate programmable Siemens S7-1200 avec module IHM TP700 Comfort. Programmation complète pour gestion process biogaz (régulation T°, pH, brassage, alimentation, sécurités). Supervision SCADA incluse avec historiques et alarmes. Reconditionné par intégrateur agréé, logiciel et documentation fournis. Formation possible.",
        "year": "2020",
        "manufacturer": "Siemens",
        "contact_email": "automation.hdf@example.fr",
        "contact_phone": "+33 3 20 XX XX XX",
        "image": "https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?w=1200&q=80",
    },
    {
        "id": 7,
        "title": "Compresseur biogaz à vis 55 kW",
        "category": "Compression",
        "location": "Pays de la Loire, FR",
        "price": "18 500 €",
        "condition": "Bon état",
        "summary": "Compresseur rotatif à vis, 55 kW, 2018.",
        "description": "Compresseur rotatif à vis lubrifié pour biogaz brut, moteur 55 kW, débit 180 m³/h à 8 bars. Mise en service 2018, révision générale effectuée en 2025. Carter inox anti-corrosion, refroidissement eau. Tableau électrique et variateur de fréquence inclus. Idéal pour injection réseau ou stations GNV. Démonté et prêt à expédier.",
        "year": "2018",
        "manufacturer": "Atlas Copco",
        "contact_email": "paysdelaloire.bio@example.fr",
        "contact_phone": "+33 2 40 XX XX XX",
        "image": "https://images.unsplash.com/photo-1581092918484-8c38d9f0f88e?w=1200&q=80",
    },
    {
        "id": 8,
        "title": "Désulfurisation biologique charbon actif",
        "category": "Épuration",
        "location": "Occitanie, FR",
        "price": "3 200 €",
        "condition": "Très bon état",
        "summary": "Colonne désulfurisation 500 m³/h, biologique.",
        "description": "Système de désulfurisation biologique du biogaz, capacité 500 m³/h. Colonne garnie de charbon actif imprégné, efficacité >99% sur H2S. Débit d'air micro-aération automatique, humidificateur intégré. Très bon état, utilisé 3 ans seulement. Permet injection réseau ou protection moteurs cogénération. Média filtrant inclus (50% vie résiduelle).",
        "year": "2021",
        "manufacturer": "BioControl",
        "contact_email": "occitanie.methanisation@example.fr",
        "contact_phone": "+33 5 61 XX XX XX",
        "image": "https://images.unsplash.com/photo-1581092918484-8a9d8b7f5a6e?w=1200&q=80",
    },
    {
        "id": 9,
        "title": "Cuve de stockage digestat 150 m³",
        "category": "Stockage",
        "location": "Centre-Val de Loire, FR",
        "price": "22 000 €",
        "condition": "Comme neuf",
        "summary": "Cuve PEHD 150 m³ avec couverture étanche.",
        "description": "Cuve de stockage digestat en polyéthylène haute densité (PEHD), volume 150 m³. Installation 2024, très peu utilisée suite changement projet. Couverture double membrane étanche gaz incluse. Brasseur lent optionnel disponible (+2500€). Système de récupération biogaz. Résiste UV et corrosion. Conforme normes environnement. Démontage et transport à prévoir.",
        "year": "2024",
        "manufacturer": "Sotralentz",
        "contact_email": "centreval.biogas@example.fr",
        "contact_phone": "+33 2 38 XX XX XX",
        "image": "https://images.unsplash.com/photo-1581092918484-8d2f8c3e4b5e?w=1200&q=80",
    },
    {
        "id": 10,
        "title": "Séparateur à vis pour digestat",
        "category": "Séparation",
        "location": "Nouvelle-Aquitaine, FR",
        "price": "8 900 €",
        "condition": "Révisé",
        "summary": "Séparateur mécanique 20 m³/h, vis inox.",
        "description": "Séparateur à vis sans fin pour séparation phase solide/liquide du digestat. Capacité 20 m³/h, vis et grille en inox 316L. Révision complète 2025 (moteur réducteur, roulements, grille). Siccité solide 25-30%. Réduction volume stockage et valorisation agronomique optimisée. Compact et fiable, faible consommation électrique 3 kW.",
        "year": "2016",
        "manufacturer": "Bauer",
        "contact_email": "nouvelleaquitaine@example.fr",
        "contact_phone": "+33 5 55 XX XX XX",
        "image": "https://images.unsplash.com/photo-1581092918484-8f3d5e4c5e5e?w=1200&q=80",
    },
    {
        "id": 11,
        "title": "Cogénérateur biogaz 250 kWe",
        "category": "Cogénération",
        "location": "Auvergne-Rhône-Alpes, FR",
        "price": "Sur devis",
        "condition": "Révisé",
        "summary": "Groupe électrogène biogaz 250 kWe, 2015.",
        "description": "Module de cogénération biogaz MWM TCG 2016 V12, puissance électrique 250 kWe, thermique 280 kWth. Année 2015, 45 000 heures de fonctionnement. Révision majeure effectuée (culasses, pistons, échappement, échangeurs). Prêt à fonctionner. Contrat de maintenance disponible. Rendement électrique 39%, global 85%. Très fiable pour valorisation biogaz agricole.",
        "year": "2015",
        "manufacturer": "MWM (Caterpillar)",
        "contact_email": "aura.energie@example.fr",
        "contact_phone": "+33 4 72 XX XX XX",
        "image": "https://images.unsplash.com/photo-1581092918484-9c8d4f5e5e5e?w=1200&q=80",
    },
    {
        "id": 12,
        "title": "Analyseur biogaz en ligne CH4/CO2/O2",
        "category": "Analyse",
        "location": "Île-de-France, FR",
        "price": "4 700 €",
        "condition": "Bon état",
        "summary": "Analyseur multicomposants en continu.",
        "description": "Analyseur de biogaz en ligne, mesure continue CH4, CO2, O2, H2S. Technologie infrarouge + électrochimique. Étalonnage automatique, enregistrement données. Utilisé 4 ans, état fonctionnel parfait. Idéal pour optimisation process et contrôle qualité biométhane. Logiciel de supervision inclus. Livré avec certificat d'étalonnage récent.",
        "year": "2020",
        "manufacturer": "Geotech",
        "contact_email": "idf.instrumentation@example.fr",
        "contact_phone": "+33 1 69 XX XX XX",
        "image": "https://images.unsplash.com/photo-1581092918484-9b8d5f6e6e6e?w=1200&q=80",
    },
    {
        "id": 13,
        "title": "Broyeur déchets organiques 15 m³/h",
        "category": "Prétraitement",
        "location": "Provence-Alpes-Côte d'Azur, FR",
        "price": "12 500 €",
        "condition": "Très bon état",
        "summary": "Broyeur à couteaux rotatifs, 15 m³/h.",
        "description": "Broyeur à couteaux pour prétraitement substrats méthanisation. Capacité 15 m³/h, couteaux acier haute résistance, granulométrie réglable 10-50mm. État excellent, très peu utilisé (installation surdimensionnée). Moteur 22 kW, alimentation trémie avec vis sans fin. Idéal biodéchets, résidus cultures, déchets IAA. Nettoyage facile, maintenance simple.",
        "year": "2023",
        "manufacturer": "Komptech",
        "contact_email": "paca.recyclage@example.fr",
        "contact_phone": "+33 4 91 XX XX XX",
        "image": "https://images.unsplash.com/photo-1581092918484-8c9d5e7e7e7e?w=1200&q=80",
    },
    {
        "id": 14,
        "title": "Pompe doseuse polymère floculation",
        "category": "Pompage",
        "location": "Grand Est, FR",
        "price": "890 €",
        "condition": "Neuf",
        "summary": "Pompe péristaltique 0-100 L/h, neuve.",
        "description": "Pompe doseuse péristaltique pour injection polymère de floculation. Débit réglable 0-100 L/h, précision ±1%. Neuve, jamais utilisée (commande annulée). Contrôle débit, affichage digital, signaux 4-20mA. Tuyau renforcé inclus. Idéal pour optimiser séparation phase digestat ou traitement eaux. Garantie constructeur 2 ans.",
        "year": "2026",
        "manufacturer": "ProMinent",
        "contact_email": "grandest.process@example.fr",
        "contact_phone": "+33 3 87 XX XX XX",
        "image": "https://images.unsplash.com/photo-1581092918484-8f9d6e8e8e8e?w=1200&q=80",
    },
    {
        "id": 15,
        "title": "Débitmètre massique biogaz DN100",
        "category": "Instrumentation",
        "location": "Flandre, BE",
        "price": "3 600 €",
        "condition": "Comme neuf",
        "summary": "Débitmètre thermique massique DN100, 2023.",
        "description": "Débitmètre massique thermique pour biogaz, diamètre nominal DN100 (4 pouces). Technologie thermique, mesure directe en Nm³/h indépendante de la pression/température. Installation 2023, état impeccable. Sortie analogique 4-20mA + Modbus RTU. Gamme 0-1000 Nm³/h. Précision ±1,5%. Documentation et certificat constructeur disponibles.",
        "year": "2023",
        "manufacturer": "Endress+Hauser",
        "contact_email": "flandre.biogas@example.be",
        "contact_phone": "+32 3 XXX XX XX",
        "image": "https://images.unsplash.com/photo-1581092918484-9c8e5f7f7f7f?w=1200&q=80",
    },
]
